# Generated by Django 4.1.5 on 2023-01-21 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_order_id_alter_user_first_name_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.supplier'),
        ),
    ]
