# Generated by Django 4.1.5 on 2023-01-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_order_supplier_order_supplier_x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='supplier_x',
            new_name='supplier',
        ),
    ]
